# NumPy库快速入门
叶璨铭, 12011404@mail.sustech.edu.cn
本笔记参考 [NumPy中文网](https://www.numpy.org.cn/user/quickstart.html#%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86)

In [2]:
import numpy as np

NumPy的主要对象是同构多维数组。它是一个元素表（通常是数字），所有类型都相同，由非负整数元组索引。在NumPy维度中称为 轴 。

3D空间中的点的坐标[1, 2, 1]具有一个轴。该轴有3个元素，所以我们说它的长度为3.
[[ 1., 0., 0.],
 [ 0., 1., 2.]]有两个轴，第一轴就是认为他是一维数组，第一眼看下去，是有两个元素。所以第一轴的长度为2，第二轴的长度为3。

## 数组创建

In [14]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(len(a))
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))
a = np.arange(0,2*np.pi,0.01)
print(a)
a = np.linspace( 0, 2*np.pi, 100 )
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
3
2
int32
4
15
<class 'numpy.ndarray'>
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11
 1.12 1.13 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25
 1.26 1.27 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39
 1.4  1.41 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53
 1.54 1.55 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67
 1.68 1.69 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1

In [4]:
b = np.array([1, 2, 3])
print(b.shape)
b = np.array([(1,2), [3,4]], dtype=complex)
print(b.shape)
c = np.empty( (2,3,4), dtype=np.int16)
print(c)

(3,)
(2, 2)
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


## 基本操作

In [5]:
# a = np.linspace(20, 51, 4)
a = np.arange(20, 51, 10)
b = np.arange(4)
print(a-b)
print(b**2)
print(a<35)
print(a*b)
print(a@b)
print(a.dot(b))

[20 29 38 47]
[0 1 4 9]
[ True  True False False]
[  0  30  80 150]
260
260


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [6]:
a = np.ones(3, dtype=np.int32)
try:
    a+=1.2 # 不同类型，无法进行自己修改的操作。
except:
    print("确实不行")
print(a + 1.2) # 但是这样可以

确实不行
[2.2 2.2 2.2]


In [8]:
import math
print(np.exp(1j * 2 * np.pi))
print(math.e**(1j * 2 *math.pi)) # 没什么区别。但是其实正确答案是1

(1-2.4492935982947064e-16j)
(1-2.4492935982947064e-16j)


In [13]:
# ndarray类的方法
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())
# 这三个函数都是幺半群，就是线段树可以用的那种。

[[0.14925461 0.24995616 0.39037577]
 [0.18998301 0.44694293 0.97878445]]
2.405296933401626
0.14925460811080216
0.9787844530445289


In [12]:
b = np.arange(12).reshape(3,4)
print(b)
c = b.sum(axis=0)  # 对第一维，也就是一行一行的这一维度，进行sum操作。所以就是所有行加起来，得到只有一行。
print(c)
print(c.shape)
c = b.sum(axis=1) #把每一列加起来，得到只有一列
print(c)
print(c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
(4,)
[ 6 22 38]
(3,)
